env:
  browser: true
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2015
  sourceType: module
extends:
  - 'eslint:recommended'
  - prettier
plugins:
  - prettier
rules:
  complexity: warn
  curly: error
  eqeqeq: error
  new-cap:
    - error
    - capIsNew: false
  no-array-constructor: error
  no-await-in-loop: warn
  no-console: warn
  no-extend-native: error
  no-eval: error
  no-implicit-coercion: error
  no-invalid-this: error
  no-lonely-if: error
  no-multi-assign: error
  no-multi-str: error
  no-param-reassign: error
  no-path-concat: error
  no-sequences: error
  no-throw-literal: error
  no-unused-vars:
    - error
    - vars: all
      args: none
      ignoreRestSiblings: false
  no-warning-comments: warn
  prefer-const: error
  prefer-spread: error
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: all
      jsxBracketSameLine: true
  require-jsdoc: warn
  sort-imports: error
  sort-keys: error
  spaced-comment: error
  symbol-description: error
  valid-jsdoc:
    - error
    - prefer:
        return: return
      preferType:
        object: Object
      requireParamDescription: false
      requireReturn: false
      requireReturnDescription: false
